### ISSUE TITLE
Style/CommentIndentation analyzes commented out methods

### ISSUE THREAD

**Issue by zenspider** [bbatsov/rubocop#1730]
```ruby
class TestPng::TestColor < Minitest::Test
#   def test_values
#     raise NotImplementedError, 'Need to write test_values'
#   end
end
```

gives:

```
woot.rb:4:1: C: Style/CommentIndentation: Incorrect indentation detected (column 0 instead of 2).
```

**Comment by mattjmcnaughton** [comment]
I think that rubocop's problem is not so much with the commented out code as it is with the indenting of your comments. For example, the below code has no error.

```
class TestPng::TestColor < Minitest::Test
  # def test_values
  #   raise NotImplementedError, 'Need to write test_values'
  # end
end
```

Basically, indent the #'s for the comments and you should be fine.

**Comment by Rockyspade** [comment]
i concored just indents# all fine dandy!

On Friday, March 27, 2015, Matt McNaughton <notifications@github.com> wrote:

> I think that rubocop's problem is not so much with the commented out code
> as it is with the indenting of your comments. For example, the below code
> has no error.
>
> class TestPng::TestColor < Minitest::Test
>   # def test_values
>   #   raise NotImplementedError, 'Need to write test_values'
>   # end
> end
>
> Basically, indent the #'s for the comments and you should be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/rubocop/issues/1730#issuecomment-87106365>.
>


-- 
Sent from Gmail Mobile

**Comment by zenspider** [comment]
dead is dead. it shouldn't matter how I comment out dead code, as it is dead.

**Comment by mattjmcnaughton** [comment]
My understanding of rubocop, though I might be wrong, is that the error isn't with the indenting of the commented out code, it's with the indenting of the comments themselves.

For example, the below code passes rubocop because the indentation of the comments works fine, even though the indentation of the commented out code is wrong.
```
class Test
  #      class Hi
  #          puts 'hi'
  #      end
end
```

Rubocop defines certain standards for comments (like they can't be more than 80 chars...) and it seems like indenting is one of them. 

I think you're totally right that commented good shouldn't be checked, but in my opinion it makes sense that the actual formatting of comments should be checked.

**Comment by bbatsov** [comment]
Yep, that's a feature, not a bug.

@zenspider You're an Emacs user like me, so you must know that Emacs places the comment delims at the same indent level as the code in question. I think most (good) editors behave the same way.

**Comment by zenspider** [comment]
I think in this case I had commented out the whole block (ie, col 0) and selectively brought back parts. This last bit was still left in as dead code.

**Comment by zenspider** [comment]
and that code was written ~10 years ago.. who knows what emacs did then :)

**Comment by alexdowad** [comment]
This issue should be closed.
