### ISSUE TITLE
Reporting source file name offense for Gemfile

### ISSUE THREAD

**Issue by carhartl** [bbatsov/rubocop#1814]
Using rubocop 0.30.0, when running rubocop on a Gemfile file I am getting an offense regarding the file name:

```
$ bundle exec rubocop Gemfile
Inspecting 1 file
C

Offenses:

Gemfile:1:1: C: Use snake_case for source file names.
source "https://rubygems.org"
^

1 file inspected, 1 offense detected
```

With Gemfile being part of the default includes https://github.com/bbatsov/rubocop/blob/8f3cfc6f3654294dd9be1643c7c75a2ff6cacfb2/config/default.yml#L17 this seems wrong. 

Am I using it wrong?

**Comment by jonas054** [comment]
That does seem wrong, but I have not been able to reproduce this problem. Can you try running the same thing in different project directories and see if you can figure out the context in which the problem appears?

**Comment by carhartl** [comment]
Ah, it only happens as soon as I add something to AllCops/Include, e.g.:

```
AllCops:
  Include:
    - 'config.ru'
```

I made a gist:
https://gist.github.com/carhartl/207f6bb25eab57fbd052

`$ git clone https://gist.github.com/207f6bb25eab57fbd052.git && cd 207f6bb25eab57fbd052 && bundle && bundle exec rubocop Gemfile`

Another question - I was expecting the includes to be merged with the default ones, that seems not to be the case? In that gist:

```
$ bundle exec rubocop
Inspecting 0 files


0 files inspected, no offenses detected
```

But:

```
$ bundle exec rubocop Gemfile
Inspecting 1 file
C

Offenses:

Gemfile:1:1: C: Use snake_case for source file names.
source 'https://rubygems.org'
^

1 file inspected, 1 offense detected
```

**Comment by jonas054** [comment]
I can understand that you expected the Includes to be merged, but RuboCop only merges configuration values that are hashes, not arrays. I think this behavior is better than the alternative, because if arrays were merged, it would not be possible to override such values.

One thing we could do is to let the `FileName` cop disregard file names that are not included in current configuration, but included in default configuration. But that would hide the other problem, that you unintentionally missed to include `Gemfile` in your configuration.

So I think it's best to keep the functionality as it is. Just add all the files you want to inspect to your `AllCops: Include`, except `*.rb` files and files with a ruby hashbang line, which are always included.

**Comment by carhartl** [comment]
Thanks, so it was wrong understanding of mine, closing. 

One last question, do you think `'**/config.ru'`is worth adding to the default includes?

**Comment by carhartl** [comment]
(If so I'm going to send a PR for it.)

**Comment by jonas054** [comment]
As I understand it `config.ru` is a configuration file used in rack based applications. Adding it to the default includes seems perfectly logical to me. :+1:
