### ISSUE TITLE
Implement a cop checking for space around interpolation

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/rubocop#1836]
Just noticed we still haven't done this. Style guide reference [here](https://github.com/bbatsov/ruby-style-guide/pull/429).

**Comment by glasnt** [comment]
Hello! I gave this one a red hot go, but I think it's something that rubocop hasn't had to handle before, so it's a little bit difficult to implement. My method was taking a similar existing cop and making it do my bidding, but since this is a fairly unique cop, from what I can tell, it's a little bit harder than I thought.

I tried to base it off `SpaceInsideBrackets`, but due to a lack of symbol for `#{`, or something, I couldn't get this to work. 

Then I tried a copy of `StringConversionInInterpolation`, which uses AST to create a node tree to define the structure of the statement. But in this parsing, the context within the interpolation is lost, so it can't be checked for spacing.

I'm thinking that this might be solvable with some sort of variation on a cop that can regex the direct string, because any other kind of processing will either evaluate, or lose, the context of the test. But I had trouble finding a combination of cop subtypes that would allow me to process the string itself without it being pre-parsed. 

The spec for this would be: 

```

  it 'registers an offense for spaces inside string interpolation' do
    inspect_source(cop, '"#{ v}"') 
    expect(cop.messages).to eq('Space inside string interpolation detected.')
  end

```
The test string is single double quotes wrapped in single quotes to prevent rspec resolving it, but it does limit the mixin this string invokes (for lint based cops it was `to_dstr`, which is AST, which failed)

If someone could point me at a cop that does something similar to this, or any other useful pointers, I can give this another go.

**Comment by jonas054** [comment]
> But in this parsing, the context within the interpolation is lost, so it can't be checked for spacing.

I don't quite understand this. Why can't you extract the expression within `#{}` like `StringConversionInInterpolation` does (called `final_node` there)?
Then it would be easy to call `range_with_surrounding_space(final_node.loc.expression)` and compare the size of that range to that of the original range.

**Comment by glasnt** [comment]
Ah ha! That's the kind of thing I was looking for! Thank you!

I'm building the new cop up now, expect a PR soon.

**Comment by dziulius** [comment]
Another useless cop
```yaml
Style/SpaceInsideStringInterpolation:
  Enabled: false
```

**Comment by bbatsov** [comment]
@dziulius Why so? Plenty of people find it useful.

**Comment by dziulius** [comment]
I'll illustrate my arguments with alternative:

there is cop that requires spaces about curly braces about block:
```ruby
[1, 2, 3].each { |num| puts num }
```

also a cop that requires spaces around hash curly braces
```ruby
{ key: :value }
```

And then we have a cop that forbids spaces about string interpolation curly braces.

I think that no spaces around curly braces for string interpolation is as ugly as:
```ruby
[1, 2, 3].each {|num| puts num}
```
or:
```ruby
{key: :value}
```

**Comment by bbatsov** [comment]
The other cops are configurable. Nobody implemented configuration for this cop - feel free to add it. Labelling something as useless just because you don't like is not the way to go. At the very least you can file a ticket requesting this feature.

**Comment by dziulius** [comment]
Well, first comment from my colleague after seeing this new cop was:
http://www.nooooooooooooooo.com/
