### ISSUE TITLE
Possibility to list unnecessarily disabled cops

### ISSUE THREAD

**Issue by sch1zo** [bbatsov/rubocop#1865]
We use in several places `# rubocop:disable` to whitelist certain areas of source code. The problem I see is that sometimes these comments won't get removed even though the issue was already fixed. In these situations I'd like to get an indication from rubocop that the disable call is useless and should be removed.

So for example you had a long method which could at the time not be split into several junks. It raises an issue on Metrics/MethodLength but you can't do anything about it (right now), temporary solution is to add `# rubocop:disable Metrics/MethodLength`.
On some later day the method can finally be refactored or some part can be removed which brings it below the limit for MethodLength. Unfortunately the developer didn't take the extra time to count the lines and realize that so he just left the `disable`-comment in place.
It would be great if rubocop could either show these instances as an issue them-self, indicating to the developer that he can remove the `disable`-comment. Or if this would need some more tracking a new command-line option could generate these issues.

(Hope I made it clear enough what I meant)

**Comment by jonas054** [comment]
I see exactly what you mean. Good suggestion.

The implementation is a bit difficult because the natural place to put this kind of functionality is in a new formatter, or possibly in `DisabledLinesFormatter`, and the way we call the formatters today doesn't make disabled offenses available to them.

The formatters have a [public API](https://github.com/bbatsov/rubocop#custom-formatters) that we should keep backwards compatible.

Maybe there are other ways to achieve the functionality, but they are not obvious to me.

**Comment by ivan-leschinsky** [comment]
I think, that pull-request broke detection `# rubocop:disable` comments when running without command-line interface. For example in `pronto-rubocop` https://github.com/mmozuras/pronto-rubocop/issues/13

**Comment by mmozuras** [comment]
@ivan-leschinsky it did, but that's what I get for using APIs that are not strictly official :smile: 

@bbatsov would you accept a PR that would create an official non-command-line API?
