### ISSUE TITLE
Prefer the use of the nil? predicate incorrect in rspec tests

### ISSUE THREAD

**Issue by asafbrukarz** [bbatsov/rubocop#1914]
In several RSpec tests, we write something like:

`object.should == nil` or `object.should be_nil`

Rubocop will autocorrect this to:

`object.should.nil?` which is not a valid test.

Can rubocop ignore this cop for rspec files?

**Comment by bbatsov** [comment]
I was under the impression `should == something` was deprecated a while back, as this produced Ruby warnings (`Useless use of == in void context`).  My advice is to either use `be_nil`, which is fine, or adopt the new `expect` API.

**Comment by KevinColemanInc** [comment]
This issue caused issues, because rubocop changed `object.should == nil` to `object.should.nil?` as stated above.

The older `:should` syntax is still supported and they have "no plans to ever completely remove the should syntax" [0].

Can I make a PR for ignoring this case?

[0] - https://relishapp.com/rspec/rspec-expectations/v/3-4/docs/syntax-configuration#explicitly-enable-both-syntaxes
