### ISSUE TITLE
Warnings when updating to rubocop 0.32.0

### ISSUE THREAD

**Issue by oliverklee** [bbatsov/rubocop#1957]
When running gem update, I get these warnings:

    Updating rubocop
    Fetching: rubocop-0.32.0.gem (100%)
    Successfully installed rubocop-0.32.0
    Parsing documentation for rubocop-0.32.0
    Installing ri documentation for rubocop-0.32.0
    Installing darkfish documentation for rubocop-0.32.0
    (eval):2: warning: invalid character syntax; use ?\s
    (eval):6: warning: else without rescue is useless
    Done installing documentation for rubocop after 4 seconds
    Parsing documentation for rubocop-0.32.0
    Done installing documentation for rubocop after 2 seconds

**Comment by bbatsov** [comment]
Seems like something related to the `InvalidCharacterLiteral` cop, but this hasn't been changed in a while. @jonas054 Any ideas?

**Comment by jonas054** [comment]
Looks like we get these warnings from `rdoc` due to bad code (on purpose) under `@example` in documentation comments in the files
* https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/invalid_character_literal.rb
* https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/lint/useless_else_without_rescue.rb

**Comment by bbatsov** [comment]
Guess we can ignore this.
