### ISSUE TITLE
Bug in Performance/Count

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#2080]
With this file `test.rb`:
```rb
# encoding: utf-8

# nodoc #
class A < Array
  def count(&block)
    select(&block).count
  end
end

a = A.new
a += [1, 2, 3, 4, 5, 6]
p a.count { |e| e > 1 }
```

RuboCop tells me that `An error occurred while Performance/Count cop was inspecting /Users/bquorning/Code/rubocop/test.rb.`

Extra information:

    0.32.1 (using Parser 2.2.2.5, running on ruby 2.2.2 x86_64-darwin13)

Actually, I was using the latest master, cdfb667243136b173ddbac804ded35a48d5ec53a.

**Comment by bquorning** [comment]
cc @rrosenblum

**Comment by rrosenblum** [comment]
I will look into this.

**Comment by rrosenblum** [comment]
I have a fix for this. I will put in a pull request shortly.

In the given example, the auto correct would be incorrect because of the method name.
```ruby
def count(&block)
  select(&block).count
end
```
would correct to
```ruby
def count(&block)
  count(&block)
end
```
which would be a recursive call and not function properly. To fix the code, the method would need to be renamed, the method should be removed, or the method should call `super(&block)`. 

For the fix, I am not taking into consideration that the defined method name is going to be the same as the correction.

**Comment by bquorning** [comment]
> For the fix, I am not taking into consideration that the defined method name is going to be the same as the correction.

Fine by me :+1:
