### ISSUE TITLE
Redundant Self broken for Active Record Concerns

### ISSUE THREAD

**Issue by ramaboo** [bbatsov/rubocop#2089]
```
# /app/models/concerns/lat_lng.rb
module LatLng
  extend ActiveSupport::Concern

  def lat
    coordinates.try(:[], 1)
  end

  def lat=(coordinate)
    self.coordinates = [] if coordinates.nil?
    self.coordinates[1] = coordinate
  end

  def lng
    coordinates.try(:[], 0)
  end

  def lng=(coordinate)
    self.coordinates = [] if coordinates.nil?
    self.coordinates[0] = coordinate
  end
end
```

`$ rubocop app/models/concerns/lat_lng.rb` produces: 

```
app/models/concerns/lat_lng.rb:10:5: C: Redundant self detected.
    self.coordinates[1] = coordinate
    ^^^^^^^^^^^^^^^^
app/models/concerns/lat_lng.rb:19:5: C: Redundant self detected.
    self.coordinates[0] = coordinate
```

But its wrong. The self is required there! `coordinates` is a property of the model that `includes LatLng`

**Comment by ramaboo** [comment]
Similar but slightly different issue https://github.com/bbatsov/rubocop/issues/1933

**Comment by jonas054** [comment]
Have you tried removing `self.`? What happens when you test/run the code?

**Comment by ramaboo** [comment]
Yes it of course does not work without self.

```
class Address
  includes LatLng
  #....
end

a = Address.new
a.lat = 34
```

Is how it's used. Without the self then `puts a.lat` would be nil.

**Comment by jonas054** [comment]
That sounds strange to me because the following stand-alone program prints `34` when I run it:

```ruby
require 'active_support'
require 'active_support/core_ext/object/try'

# /app/models/concerns/lat_lng.rb
module LatLng
  extend ActiveSupport::Concern

  def lat
    coordinates.try(:[], 1)
  end

  def lat=(coordinate)
    self.coordinates = [] if coordinates.nil?
    coordinates[1] = coordinate
  end

  def lng
    coordinates.try(:[], 0)
  end

  def lng=(coordinate)
    self.coordinates = [] if coordinates.nil?
    coordinates[0] = coordinate
  end
end

class Address
  include LatLng

  attr_accessor :coordinates
end

a = Address.new
a.lat = 34

puts a.lat
```
This is as expected because `a.lat = 34` calls `LatLng#lat=`, and when `coordinates[1] = coordinate` is evaluated, `coordinates` is evaluated first before `#[]=` is called on that object. If there's no local variable with the same name, `coordinates` will be called on the current object (implicit `self`).

**Comment by atz** [comment]
We also work extensively with `ActiveSupport::Concern` in our models.  I have only found a problem removing self when `self.` when the invocation was to an attribute dynamically populated (via method_missing) and the call collides with a reserved keyword.  The reason there is obvious.  But otherwise, rubocop suggests the correct action.

**Comment by mikegee** [comment]
It is important to note that Rubocop only registers an offense on the redundant usages of `self.`, not every `self.`. Refer to the example posted by @jonas054. (Setting an attribute needs the `self.` prefix to avoid declaring a new local variable.)

The `RedundantSelf` cop supports auto-correcting your code. Please try auto-correct and report if there is still an issue.
