### ISSUE TITLE
Rubocop Shows bash Color Escape Sequences in Output Files

### ISSUE THREAD

**Issue by roberts1000** [bbatsov/rubocop#2262]
I just tried running the following command with rubcop 0.34.1

````bash
rubocop --format simple --out issues.txt
````

and got the following output in the text file

````text
C: 39: 32: Use ESC[33m&&ESC[0m instead of ESC[33mandESC[0m.
````

**Comment by minustehbare** [comment]
I believe I found where this bug is occurring and can submit the fix I mention below if appropriate.  Running rspec shows a few failures/pending tests, none related to this change, and a quick test on a real file produced the correct results.

From *lib/rubocop/formatter/simple_text_formatter*:
```ruby
class SimpleTextFormatter < BaseFormatter
  include Colorizable, PathUtil, TextUtil

...

def annotate_message
  msg.gsub(/`(.*?)`/, Rainbow('\1').yellow)
end
```

In the same file, the file name/path is output in yellow using a separate syntax mixed in through `Colorizable`:
```ruby
def report_file(file, offenses)
  output.puts yellow("== #{smart_path(file)} ==")
  ...
end
```

Proposed fix:
```ruby
# this
def annotate_message
  msg.gsub(/`(.*?)`/, Rainbow('\1').yellow)
end

# to this
def annotate_message
  msg.gsub(/`(.*?)`/, yellow('\1'))
end
```
