### ISSUE TITLE
The cop correcting usage of $? to $CHILD_STATUS should mention require 'English'

### ISSUE THREAD

**Issue by whitequark** [bbatsov/rubocop#2310]
It is not obvious and your code just appears to be broken if you don't do that.

**Comment by bbatsov** [comment]
Hmm, it's supposed to do this https://github.com/bbatsov/rubocop/blob/4240ae468edbd1e1589ed3501cc16cbba3ab8513/lib/rubocop/cop/style/special_global_vars.rb#L9

**Comment by whitequark** [comment]
@jcoglan, can you confirm that the message above did not appear to you?

**Comment by jcoglan** [comment]
I've realised the problem: that message did appear but I interpreted `English` as an adjective rather than as a Ruby module; I didn't realise it meant you had to `require 'English'` to get access to those names. Could the message be clarified so it's more obvious that `English` is a package from the stdlib?

**Comment by jcoglan** [comment]
(And thanks to @whitequark to opening the issue when I was grumbling on twitter)

**Comment by alexdowad** [comment]
This has been fixed now and should be closed.

**Comment by raulccabreu** [comment]
Why this cop has auto-correct if it's required a later action from developer (put `require "English"` on file)? We rely on autocorrect and this is a case where many developers must find problems. I suggest disable auto-correct from Style/SpecialGlobalVars cop when `EnforcedStyle: use_english_names`.

**Comment by jonas054** [comment]
> Why this cop has auto-correct if it's required a later action from developer (put require "English" on file)?

Because we don't know if `English` is required somewhere else in the inspected application. This is something we can't determine due to RuboCop's file-by-file inspection algorithm. Always adding `require 'English'` in each file where the offense is found would be worse IMO. Those unnecessary `require`s are very hard to spot, whereas the missing `require`s are easily discovered.
