### ISSUE TITLE
Open text editor on each found offense

### ISSUE THREAD

**Issue by amw** [bbatsov/rubocop#2326]
Hey, I've prepared this script that helped me tremendously when I was adding RuboCop to one of my bigger projects. It basically opens an $EDITOR on each offense, waits for user to modify the file and goes to the next offense. I've tuned it for MacVim/Vim, but any $EDITOR that doesn't detach from shell should work.

Here's my gist: https://gist.github.com/amw/2235895ef6600b3d3ab1

Would you like me to reformat this and send as pull request for inclusion in the project or would you rather leave it as a gist that users can go to if they need this?

**Comment by jonas054** [comment]
In Emacs I usually run `rubocop` as a compilation and jump between offenses with the `next-error`and `previous-error` functions (bound to keys for convenience). This has the added advantage of getting the cursor at the correct position in the file.

I don't know much about the vi family of editors but I'm pretty sure something similar is possible there. And since the whole problem of jumping between errors/warnings is solved outside of RuboCop, and has been for ages, it's a waste of resources, IMO, to solve it one more time inside RuboCop. We report offenses on the standard format `<file name>:<line number>:<column>: <description>` and that's enough.

So I'd rather leave this as a gist and not include it.

**Comment by amw** [comment]
You're right. There are commands in Vim (like `:make` and `:cw` or `:lnext`) that accomplish the same task and it's probably better to keep that list traversing an editor responsibility.

Though I do have to say it was really fast just closing the MacVim window (Cmd+W) and having a new window pop up immediately.
