### ISSUE TITLE
making rubocop comments and links to urls markdown compatible

### ISSUE THREAD

**Issue by tansaku** [bbatsov/rubocop#2330]
I'm using rubocop config on hound and a comment from rubocop like this:
```
lib/customer.rb:16:81: C: Metrics/LineLength: Line is too long. [82/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    raise "Please select a dish from the menu." if !restaurant.menu_include?(dish)
                                                                                ^^
```
interprets the link as having the title "82/20" and so in markdown it looks like this:

[82/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)

I wonder if we could change the format slightly to make the output markdown friendly ...

**Comment by alexdowad** [comment]
What format do you suggest?

**Comment by tansaku** [comment]
@alexdowad well how about:

```
lib/customer.rb:16:81: C: Metrics/LineLength: [Line is too long. 82/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    raise "Please select a dish from the menu." if !restaurant.menu_include?(dish)
```

That would produce the following:

[Line is too long. 82/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)

for no immediate loss of readability in the text version I think.  However equally one could just do:

```
lib/customer.rb:16:81: C: Metrics/LineLength: Line is too long. {82/80} (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    raise "Please select a dish from the menu." if !restaurant.menu_include?(dish)
```

or anything to just avoid the `[...](...)` format that does hyperlinks in markdown.  Personally I'd go for a consistent use of [Line is too long. 82/80] (https://github.com/bbatsov/ruby-style-guide#80-character-limits) throughout all cop responses in order to make most efficient use of space in automated rubocop posts on pull requests (e.g. via hound), but of course we also want to make sure that text interface users are happy ...

what would you prefer?

**Comment by alexdowad** [comment]
Just thinking about this some more:

I'm sure GH Markdown has some way to emit a literal `[...] (...)` (not a link). Do you know what it is?

An ideal situation would be if Hound can fix up their automated GitHub post code to preprocess the output of RC, and convert `[...] (...)` to a literal.

There are a lot of CLI tools whose output would not look good if you simply cut-and-pasted it into GH as Markdown. Because... their output is *not* Markdown. When pasting excerpts from my shell into GH, I always surround them with triple backticks, for this reason.

Likewise, the output of RuboCop is *not* Markdown. Any other program or tool which takes that output, and tries to use it as Markdown without doing any preprocessing or conversion, is faulty.

The problem should be fixed at its source, rather than patching it here. Therefore, I recommend that this issue should be closed. @bbatsov @jonas054

**Comment by alexdowad** [comment]
An alternative would be to add a new formatter which outputs Markdown, rather than plain text (which is what RC's default "simple text" formatter gives you).

@tansaku, are you interested in writing a new formatter? I can guide you through the process. I believe @bbatsov would be very happy to merge it into RC. Maybe the guys at Hound may also be interested?

**Comment by bbatsov** [comment]
Yeah, probably a new formatter would be the best option.

**Comment by tansaku** [comment]
@alexdowad I would be interested in writing a new formatter, although I probably won't be able to get into it till the new year.  

I'd also love to work up a formatter that gives a report in terms of numbers of offences by category, so it showed like:

* 9 Line Length offences [click for details](...)
* 3 indentation offences [click for details](...)

but that's another story :-)

**Comment by alexdowad** [comment]
> @alexdowad I would be interested in writing a new formatter, although I probably won't be able to get into it till the new year.

It's easier than you think. But whenever you have time, that is fine.

**Comment by alexdowad** [comment]
Maintainers, I suggest you can close this issue, and @tansaku can reopen if and when he is ready to go further with the proposed new formatter.

**Comment by tansaku** [comment]
thanks @alexdowad and @bbatsov I've been on holiday for two weeks - will get into this next week I hope
