### ISSUE TITLE
Fillter the error and fatal code

### ISSUE THREAD

**Issue by awesomes-cn** [bbatsov/rubocop#2337]
I want to just find the `error` and `fatal` code and file.

So I run `rubocop ---fail-level error`

But I still see all the message.

So how can I realize this? Thanks!

**Comment by maxjacobson** [comment]
I have kind of the same issue. In my continuous integration for one app, I have rubocop run with `--fail-level W`. When a build fails due to a warning-level rubocop offense, it's not very easy to find which offense failed the build because it's among a bunch of style offenses. It's fairly clear for me, because I'm the one who added rubocop, but I worry it's less clear to my teammates.

**Comment by awesomes-cn** [comment]
You are right! If I just want to deploy the app, maybe I only  care is the code which is `error` and `fatal` ,because this will lead my app to 500,that is important.

**Comment by jonas054** [comment]
If you don't have any custom severity levels in your configuration, it's quite simple. The Synax cop reports on `fatal` and `error` level, Lint cops on `warning` level and all other cops on `convention` level.

So for only `fatal` and `error`, it's `rubocop --only Syntax` (which is only supported on master, not released yet), and for `warning`and above it's `rubocop --only Lint`.

**Comment by awesomes-cn** [comment]
Thanks!
