### ISSUE TITLE
Style/AndOr suggests invalid syntax with `or raise`

### ISSUE THREAD

**Issue by wjbuys** [bbatsov/rubocop#2375]
When using the `or` keyword for parameter nil-checking:

```
$ cat test.rb
def do_something(config:)
  @config = config or raise ArgumentError.new(":config cannot be nil")
end
```
`Style/AndOr` suggests:
```
$ rubocop --only Style/AndOr test.rb
Inspecting 1 file
C

Offenses:

test.rb:2:20: C: Use || instead of or.
  @config = config or raise ArgumentError.new(":config cannot be nil")
                   ^^

1 file inspected, 1 offense detected
```
However, making the change:
```
$ sed -i 's/or/||/' test.rb         
$ git diff
diff --git a/test.rb b/test.rb
index b020374..5b994aa 100644
--- a/test.rb
+++ b/test.rb
@@ -1,3 +1,3 @@
 def do_something(config:)
-  @config = config or raise ArgumentError.new(":config cannot be nil")
+  @config = config || raise ArgumentError.new(":config cannot be nil")
 end
```
Results in a syntax error:
```
$ rubocop --only Style/AndOr test.rb
Inspecting 1 file
E

Offenses:

test.rb:2:29: E: unexpected token tCONSTANT
  @config = config || raise ArgumentError.new(":config cannot be nil")
                            ^^^^^^^^^^^^^

1 file inspected, 1 offense detected
$ ruby -c test.rb 
test.rb:2: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
  @config = config || raise ArgumentError.new(":config cannot be nil")
                                         ^
```

Test environment:
```
$ ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
$ rubocop -v
0.34.2
```

**Comment by alexdowad** [comment]
Thank you for reporting this issue. I have just opened a PR which will make `Style/AndOr` able to autocorrect your code without breaking it. In your case, it would autocorrect to:

```ruby
(@config = config) || raise(ArgumentError.new(":config cannot be nil"))
```

Whether you like this style or not is another question!

**Comment by wjbuys** [comment]
Thanks for the prompt response. 

`or raise` (or `or fail`, if you prefer) is actually a [fairly natural use of the `and/or` statement modifiers](http://devblog.avdi.org/2010/08/03/and-and-or-are-like-backwards-statement-modifiers/), and reads very clearly and concisely for this sort of use case. Does the AST have enough information to detect the `or raise` case? Would it be possible to add configuration to allow the `or raise|fail` case specifically, or the `or method_call argument, [argument]` case in general?

Also, just to be clear, that commit message seems a bit misleading: the problem is not caused by the assignment specifically, but rather the fact that ruby doesn't allow:

```
boolean_var || method_call SomeClass.new
```
... because that evaluates as:
```
(boolean_var || method_call) SomeClass.new
```
... which is invalid, and why the many extra parens are necessary.

**Comment by alexdowad** [comment]
@wjbuys, allow me to correct you: the assignment was indeed the problem. The Ruby code `a = 1 or blah` parses as `(a = 1) or blah`, whereas `a = 1 || blah` parses as `a = (1 || blah)`.

RuboCop was *already* able to correct the issue which you describe above. However, it did not know what to do with the assignment on the LHS. That is why it would not autocorrect the code. Try putting parens around the assignment and then run `rubocop -a`; you will see what I mean.

What you say about `or` being appropriate in some cases is reasonable. However, the current behavior of `Style/AndOr` is to complain about it in all cases. In line with the current design of `Style/AndOr`, the above commit enhances `Style/AndOr` so that it can autocorrect in almost all cases where it complains. This helps to address the issue you reported; you tried to correct according to the warning, and it broke your code.

If you feel that `Style/AndOr` should be made configurable to accept a different style, that is a separate issue and I recommend that you report it as one. You should include a proposal of exactly which cases should use `or`, and which should use `||`.

Thanks again!

**Comment by daviddavis** [comment]
I think the Style/AndOr cop can already be configured for @wjbuys's case:

https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L164

**Comment by wjbuys** [comment]
@alexdowad ah, I see. Thanks for clarifying.
@daviddavis unfortunately, assignments are exactly where `and/or` are the most dangerous:

```ruby
value = false or true
value #=> false
#vs
value = false || true
value #=> true
```

I'll open a feature request for configuring `Style/AndOr` once I have some more time to formulate it.
