### ISSUE TITLE
Style/SpaceAroundOperators Autofix Joins Lines

### ISSUE THREAD

**Issue by jfelchner** [bbatsov/rubocop#2538]
If you autofix `Style/SpaceAroundOperators` with this code:

```ruby
my_string = 'Here is a'+
            'joined string'+
            'across three lines'
```

it gets autofixed to this:

```ruby
my_string = 'Here is a' + 'joined string' + 'across three lines'
```

instead of this:

```ruby
my_string = 'Here is a' +
            'joined string' +
            'across three lines'
```

**Comment by alexdowad** [comment]
Just pushed a fix.

**Comment by alexdowad** [comment]
Thanks for the report, by the way!

**Comment by jfelchner** [comment]
@alexdowad man you've been killin it lately! Thanks!

**Comment by alexdowad** [comment]
:smile: Just trying to push this gem forward to the 1.0 release. There is a **lot** to do. Clearing all these issues is just the first step.

**Comment by jfelchner** [comment]
Well then I'll try to keep mine down to a minimum. :) Let me know if you want to pair on any issues!

**Comment by alexdowad** [comment]
> Well then I'll try to keep mine down to a minimum.

No, please keep them coming. We need to find out about anything that doesn't work properly, or any serious "gaps" in what RC is able to check.

> Let me know if you want to pair on any issues!

We definitely need more people working on the code. I would suggest that rather than pairing, if you would like to pick any issue which you are interested in working on, I can give you some guidance on how to start, and help if/when you get stuck.
