### ISSUE TITLE
Inconsistence between ruby-style-guide for fail/raise and rubocop implementation

### ISSUE THREAD

**Issue by afdev82** [bbatsov/rubocop#2732]
I noticed that rubocop has a dead link to https://github.com/bbatsov/ruby-style-guide#fail-method and the current rule in the README (https://github.com/bbatsov/ruby-style-guide#prefer-raise-over-fail) is exactly the contrary of what rubocop currently checks.
I think we should align the implementation to the guide.

**Comment by stamhankar999** [comment]
+1 to do *something* here. I ran rubocop on my code yesterday and noticed many raise's turned into fail's. I googled raise vs. fail, and found https://www.relishapp.com/womply/ruby-style-guide/docs/exceptions, which implies that rubocop's behavior is correct. But as you said, the style guide in RuboCop says otherwise.

The question of how to proceed boils down to which style guide we follow. If relishapp, then we should update the style-guide that bbatsov wrote. If the bbatsov guide wins, then rubocop impl should be updated.

**Comment by alexdowad** [comment]
Is there any objective reason to prefer one over the other? Or is it just a case of picking whichever one seems more descriptive?

**Comment by bbatsov** [comment]
It should be addressed by making `raise` the default in RuboCop. The guide was recently updated after years of debating the subject.

**Comment by bbatsov** [comment]
> Is there any objective reason to prefer one over the other? Or is it just a case of picking whichever one seems more descriptive?

There are reasons, but they aren't important for this particular ticket. :-) I'm fine with always using `raise` and it seems the majority of people are doing this anyways.
