### ISSUE TITLE
Style/RedundantReturn reports error in case of return after a loop

### ISSUE THREAD

**Issue by ojab** [bbatsov/rubocop#2853]
For code like
```ruby
def tst
  [1].each {}
  return
end
```
rubocop (0.37.2 (using Parser 2.3.0.6, running on ruby 2.3.0 x86_64-darwin15)) reports
```
/tmp/1.rb:3:3: C: Style/RedundantReturn: Redundant return detected.
  return
  ^^^^^^
```
although this method will return `[1]` instead of `nil` if  `return` will be removed.

**Comment by maxjacobson** [comment]
if you write it as:

```ruby
def tst
  [1].each { }
  nil
end
```

There shouldn't be an offense. I'm not sure which version is more beautiful, but this version is arguably more explicit about the return value

**Comment by mikegee** [comment]
@maxjacobson's rewrite is also how Rubocop corrects the code.

I also prefer seeing the return value at the bottom of the method, rather than implying it by calling `return` with no arguments.

You could turn off `Style/RedundantReturn` for your project or inline on that one `return`.

BTW, when I want to enforce command query separation and not return a useful value from a "command" method, I chose to return `self`. Returning `self` also enables chaining multiple commands together.

**Comment by ojab** [comment]
Hmm, why this issue was closed? Workarounds does't mean that there isn't a bug.

**Comment by mikegee** [comment]
Well autocorrect doesn't remove the `return` as the message seems to imply. So, I'm not sure it is really is a bug. (Unless unclear messages are considered bugs.) Perhaps you can help devise a clearer message for this?

**Comment by ojab** [comment]
Ah, I've reread comments and now I see that it's the message issue, not actually a bug. Sorry for the noise.
