### ISSUE TITLE
Style/SymbolProc suggestion breaks code.

### ISSUE THREAD

**Issue by jcoyne** [bbatsov/rubocop#3071]
I have an ActiveRecord model with the following callback:

``` ruby
    before_destroy do |obj|
      obj.remove_file!
    end
```

When I run rubocop it gives this suggestion.

```
Style/SymbolProc: Pass &:remove_file! as an argument to before_destroy instead of a block.
    before_destroy do |obj| ...
                   ^^^^^^^^
```

If I run `rubocop -a` on this it rewrites it as:

``` ruby
before_destroy(&:remove_file!)
```

Now when I run the code it gives me:

```
    ArgumentError:
       no receiver given
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:292:in `destroy'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:281:in `block in destroy'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
     # /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:281:in `destroy'
```

```
rubocop -v
0.39.0
```

**Comment by rrosenblum** [comment]
Unfortunately, I think this falls into a special case. It has been a while since I have read information on this, but if I remember correctly, this has to do with the symbol proc and the block technically doing slightly different things. I believe it has something to do with the scope of what the block is called on vs the scope of what the proc is called on. 

Maybe `ActiveRecord`'s implementation of `to_proc` needs to be tweaked. http://benjamintan.io/blog/2015/03/16/how-does-symbol-to_proc-work/

I am going to need some other people to weigh in on this as well.

**Comment by jcoyne** [comment]
It looks to me like rubocop is assuming too much about the behavior from the method by looking at it's call structure.  I don't think it should make these huge assumptions about how the code works.

**Comment by owst** [comment]
While I can't really comment on how to solve the issue, for the interested, I've done a bit of reading to see what's actually going wrong with this transformation. With a small amount of hand waving, I think I can explain it. It's a bit, long, so here goes. Consider:

```
irb(main):001:0> def block_arity(&blk)
irb(main):002:1>   puts "blk arity is: #{blk.arity}"
irb(main):003:1> end
=> :block_arity
irb(main):004:0> block_arity { |obj| obj.remove_file! }
blk arity is: 1
=> nil
irb(main):005:0> block_arity(&:remove_file!)
blk arity is: -1
=> nil
```

(side-note 1, `arity`'s behaviour is [quite involved!](http://ruby-doc.org/core-2.3.0/Proc.html#method-i-arity)).

We can assume that the definition of `Symbol#to_proc` is something like:

```
class Symbol
  def to_proc
    Proc.new {|*args| args.shift.send(self, *args) }
  end
end

```

Then we can see where `-1` comes from:

```
irb(main):001:0> Proc.new { |*args| }.arity
=> -1
```

(side-note 2: in fact, at least for MRI, `to_proc` is actually defined in C, [here](https://github.com/ruby/ruby/blob/ruby_2_3/proc.c#L600). The code to handle calling the resulting procs is [here](https://github.com/ruby/ruby/blob/ruby_2_3/string.c#L9131), and that's where the `no receiver given` error comes from.)

Now, looking at the source of ActiveSupport, using the backtrace from @jcoyne's example we [see this](https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/callbacks.rb#L445):  

```
if filter.arity <= 0
  lambda { |target, _| target.instance_exec(&filter) }
else
  lambda { |target, _| target.instance_exec(target, &filter) }
end
```

Indeed, the code is doing something subtly different if given a block of 0/negative arity: not passing the target object to `instance_exec`. Now, we can now emulate the problem ourselves:

```
irb(main):001:0> class Greeter
irb(main):002:1>   def greet!
irb(main):003:2>     puts 'hi!'
irb(main):004:2>   end
irb(main):005:1> end
=> :greet!
irb(main):006:0> greeter = Greeter.new
=> #<Greeter:0x007fe963ec4c40>
irb(main):007:0> greeter.instance_exec(greeter, &:greet!)
hi!
=> nil
irb(main):008:0> greeter.instance_exec(&:greet!)
ArgumentError: no receiver given
	from (irb):8:in `instance_exec'
	from (irb):8
```

The [definition of `instance_exec`](http://ruby-doc.org/core-2.2.2/BasicObject.html#method-i-instance_exec) tells us `Arguments are passed as block parameters` - if we give no arguments, we get no parameters passed to the block, which means that `*args` (or the C-equivalent) is empty, and thus there is no receiver upon which to `send(self)`, and bang!

I have no idea *why* ActiveSupport changes behaviour based on the arity of the block - I'd love to know!

So, the `Style/SymbolProc` transformation is only safe if the method does *not* perform different computation depending on the arity of the block/proc. Because `before_create` *does* do this, there is a problem. 

Now, I'm not sure what could be done about this. In general I think the `Style/SymbolProc` cop is useful and gives a nice improvement. And since rubocop is a static analysis tool, it can't know what the method's implementation is (and in particular whether it changes behaviour based on `#arity` or not). So, clearly in general this cop can't autocorrect all source without causing breakage.

There must be similar examples in other cops, I wonder if @bbatsov can give any insight in to how they're handled?

**Comment by rrosenblum** [comment]
@jcoyne, `SymbolProc` supports a configurable list of `IgnoredMethods`. I suggest adding `before_destroy`, and other hooks, to this list. Aside from RuboCop potentially adding these by default, or `ActiveSupport` modifying its `to_proc`, I do not think there is a fix for this. Unfortunately, this issue goes beyond static code analysis.

@owst, excellent job on the research. Interesting information. I have seen `ActiveSupport` do some strange things in the past. Each release tends to have some major improvements. Maybe/hopefully this can be corrected internally. It would take some digging through their code and tests to figure out what is being done and if and how it could be changed.

**Comment by Drenmi** [comment]
The current solution is to add Rails callbacks which change `Symbol#to_proc` to the `IgnoredMethods` list. 

There is a suggestion to create a recommended configuration for Rails projects. This should be part of that.  🙂
