### ISSUE TITLE
Relative Exclude 

### ISSUE THREAD

**Issue by jshirley** [bbatsov/rubocop#3145]
The `Exclude` relative pathing seems broken based upon where you run rubocop from. I mostly want to confirm that this behavior is broken, and if so I can try to find some time to apply a patch. I've never looked at rubocop source and may be about as quick as a sloth stuck in velcro.

Thanks!

## Expected behavior

In an inherited `.rubocop-todo.yml` file, if you have an `Exclude` block and run rubocop from in that directory tree, to continue to treat the `Exclude`d files as relative to the `.rubocop.yml` (or `.rubocop-todo.yml` if inherited)

## Actual behavior

The exclusion fails, unless I have an entry for the specific file without the directory (`some/path/foo.rb` *and* `foo.rb` listed as `Exclude`s)

## Steps to reproduce the problem

I setup a [gist](https://gist.github.com/jshirley/e1cdfd0e5dd04612d112e4675d038a91)!

```shell
git clone https://gist.github.com/jshirley/e1cdfd0e5dd04612d112e4675d038a91 rubocop-bug-report
cd rubocop-bug-report
bundle
mkdir -p rel/path && mv broken.rb rel/path # gist doesn't allow subdirectories
bundle exec rubocop rel/path/broken.rb # this works, as expected
cd rel/path
bundle exec rubocop broken.rb # this should pass!
```

## RuboCop version

```
$ rubocop -V
0.40.0 (using Parser 2.3.1.0, running on ruby 2.1.2 x86_64-darwin15.0)
```

**Comment by jshirley** [comment]
I started digging in a little bit, and looking at [`base_dir_for_path_parameters`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/config.rb#L187), it is converting `.rubocop-todo.yml` into `.rubocop_todo.yml`, which obviously doesn't match (therefor it is returning `Dir.pwd`).

If I rename my file to `.rubocop_todo.yml` everything works as expected.

I will continue investigating why the conversion from `-` to `_` is happening.

**Comment by jonas054** [comment]
Exclude paths are relative to the file where they are given only for `.rubocop.yml` and `.rubocop_todo.yml`. For other files they are relative to the current directory, and this is by design so that paths given in `.../rubocop/config/default.yml`, for example, are relative to where you run. So use the standard naming `.rubocop_todo.yml` and you'll be fine.

There is no conversion of names BTW. The message `Attention: rubocop_todo.yml has been renamed to .rubocop_todo.yml` means that RuboCop changed how it names the todo-file at one point.

**Comment by jshirley** [comment]
Ah, I see now. Thanks!
