### ISSUE TITLE
undefined method `begin' for #<Parser::Source::Map::Operator:0x007fbe95fd5678>

### ISSUE THREAD

**Issue by apsalin** [bbatsov/rubocop#3684]
echo "c = ('a'.starts_with? 'X') || ('b'.starts_with? 'Y') ? 120 : 210" | rubocop --stdin --auto-correct -

fails with this error:

undefined method `begin' for #Parser::Source::Map::Operator:0x007fbe95fd5678
...
## Steps to reproduce the problem

echo "c = ('a'.starts_with? 'X') || ('b'.starts_with? 'Y') ? 120 : 210" | rubocop --stdin --auto-correct -
## RuboCop version

> rubocop -V
> 0.42.0 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin15)

**Comment by rrosenblum** [comment]
I was able to reproduce the issue in RuboCop 0.42.0. This appears to have been fixed in 0.44.0. The error that you are seeing is coming from `Style/TernaryParentheses`. I think that this was fixed in #3513. Try upgrading RuboCop and see if you still encounter any issue. The current version is 0.45.0

**Comment by apsalin** [comment]
thank you, update to 0.45.0 fixed it
