### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by bquorning** [bbatsov/rubocop#3930]
There have been 7 bugs fixed following the release of v0.47.0 yesterday. Will you consider releasing a v0.47.1?

**Comment by backus** [comment]
:+1:. This would be especially nice since the bug that clobbers `RSpec/FilePath` (with `Rails/FilePath`) makes it impossible for rubocop-rspec users to configure one of our cops. This usually wouldn't be terrible but it also then blocks them from upgrading RuboCop because we had to do a release that fixed a few parts of the rubocop codebase that we depended on which were refactored recently.

**Comment by bbatsov** [comment]
This was already on my agenda. There'll be a new bugfix release soon.
