### ISSUE TITLE
Feature Request: Ignore case-sensitivity in control comments

### ISSUE THREAD

**Issue by rnelson0** [bbatsov/rubocop#3934]
When using control comments to disable or enable cops, you must currently be case sensitive. For example, `#rubocop:disable RSpec/RepeatedExample` disables the check vs `#rubocop:disable Rspec/RepeatedExample`, which does nothing. There appears to be no likelihood of conflicts in case sensitivity, nor would there be good reason for such a conflict. Please allow case-insensitivity so that both of the above examples result in disabling the same check. 

When creating a check, a case-insensitive comparison against existing checks should be performed as well. This would be independent of the requested feature above, as even with case-sensitivity, no two checks should exist that have similar titles except case-sensitivity, or it would cause end-user confusion.

**Comment by rnelson0** [comment]
*sigh* nevermind, this appears to exist already and I had a typo in `robocop` 👎

**Comment by backus** [comment]
If you're on the latest rubocop (0.47.1) and rubocop-rspec (1.10.0) then it should let you know that you have an invalid namespace if you put `Rspec` instead of `RSpec`. It should also let you drop the namespace entirely as long as it isn't a cop name existing under multiple namespaces like `Rails/FilePath` and `RSpec/FilePath`. This was actually *just* fixed in the latest release so glad to hear it works.

**Comment by rnelson0** [comment]
FWIW it didn't complain about Rspec vs RSpec (at least not that was visible
to me) but it disabled the cop for me anyway!

**Comment by backus** [comment]
Interesting. The exact behavior of the department resolving code continues to elude me...
