### ISSUE TITLE
.spec pattern clashes with RPM spec files

### ISSUE THREAD

**Issue by iainbeeston** [bbatsov/rubocop#4553]
## Expected behavior

I'd expect rubocop to only parse ruby files, and ignore any files that are not ruby files.

## Actual behavior

Rubocop is trying to parse ".spec" files in my project's node_modules directory, which are rpm spec files, not ruby files, and it throws an error because it cannot parse them.

## Steps to reproduce the problem

I've added a sample rails app that reproduces the issue [here](https://github.com/iainbeeston/rubocop-test), which has a travis build to show the issue [here](https://travis-ci.org/iainbeeston/rubocop-test)

To reproduce manually:

1. `rails new --webpack=react foo`
2. `cd foo`
2. Add rubocop to Gemfile
3. `bundle install`
4. `bundle exec rake yarn:install`
3. `rubocop`

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-darwin16)
```

**Comment by iainbeeston** [comment]
I can see that by default `rubocop` loads `.spec` files in [`config/default.yml`](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L29). I'm hoping that they are a legacy feature and can be safely removed?

Another alternative would be to exclude `node_modules/**/*` by default

**Comment by Drenmi** [comment]
RuboCop tries to make as few library specific exceptions as possible, since it is a *Ruby* analyzer. That said, having a `node_modules` in the same directory is not really library specific, and I personally (I'm not a maintainer) wouldn't be opposed to having this ignored by default. (The chance of someone having a directory, `node_modules`, with Ruby code is practically 0.) 🙂 

Care to make a PR to have it tested? 🙂
