### ISSUE TITLE
PVS rules in rubocop

### ISSUE THREAD

**Issue by igalic** [bbatsov/rubocop#4591]
Currently rubocop implements a number of style checks for performance security, as well as general clean-code guidelines like cyclomatic complexity.

I was wondering how hard it would be to implement a few common … ***programmer*** errors, as documented by the PVS Project: https://www.viva64.com/en/examples/

There are numerous that are not C/C++/C# specific.

For example: https://www.viva64.com/en/w/V571/

**Comment by Drenmi** [comment]
Great resource! I immediately saw one I like: identical operands in binary operations.

To answer your question: Yes. RuboCop already has a bunch of `Lint` and `Style` cops that checks for these kinds of mistakes. 🙂 

I hope that answers the higher level question. I'm going to close this issue since there's no immediate action, but if there are specific checks that you think make sense for Ruby, and are keen on seeing, please open an issue asking for that particular feature. 🙂 

Thanks!

**Comment by igalic** [comment]
@Drenmi basically, the example I provide is definitely not implemented, or otherwise it would've caught *a lot* of my bugs 😁 

most of the issues i mean are caused by sloppy copy/paste/edit, where the edit part is neglected, usually (only) on the last line/expression:

* [V501. There are identical sub-expressions to the left and to the right of the 'foo' operator.](https://www.viva64.com/en/examples/V501/), as you mention yourself
* [V517. The use of 'if (A) {...} else if (A) {...}' pattern was detected. There is a probability of logical error presence.](https://www.viva64.com/en/examples/V517/)
* [V524. It is odd that the body of 'Foo_1' function is fully equivalent to the body of 'Foo_2' function.](https://www.viva64.com/en/examples/V517/) (go linters also have this)
* [V571. Recurring check. This condition was already verified in previous line.](https://www.viva64.com/en/examples/V571/) — the one i lead with
