### ISSUE TITLE
No autocorrect for Lint/EmptyWhen

### ISSUE THREAD

**Issue by ceclinux** [bbatsov/rubocop#4684]
Feel curious about why there is no autocorrect for Lint/EmptyWhen. It seems remove the empty when branches will do the work.

**Comment by jonas054** [comment]
Most `Lint` cops don't have auto-correct and the reason is that they usually warn about possible bugs. These offenses should not be "swept under the rug". The user needs to take a look, because an empty `when` isn't necessarily an extraneous `when`. It could be that something is missing/forgotten after the `when`.
