### ISSUE TITLE
Recommendation regarding dependencies in Gemfile / .gemspec

### ISSUE THREAD

**Issue by erwanlr** [bbatsov/rubocop#4739]
Hey there,

I have been trying to find information regarding how to handle the dependencies in the Gemfile / .gemspec in the best way, without much success for the case I will describe below. Feel free to redirect me to any relevant article you might know of.

The question would be whether or not to include the dependencies (and to which extend, i.e. with versions restriction or not) needed BUT which are already meet in another required gem.

For example, using the opt_parse_validator gem (https://github.com/wpscanteam/OptParseValidator/blob/master/opt_parse_validator.gemspec) along with addressable:

```ruby
# snipped .gemspec
s.add_dependency 'addressable', '~> 2.4.0'
s.add_dependency 'opt_parse_validator', '~> 0.0.13.5'

# snipped script file
require 'addressable'
require 'opt_parse_validator'
```

So far this was logical to me. However, recently, after a ```gem update```, a conflict emerged due to addressable being required by opt_parse_validator and this script, but with different version restriction. And to make it worse, the real case scenario of this simplified example involves opt_parse_validator being required by the cms_scanner gem, which is then required by wpscan v3 gem. Quite a nightmare to have to update all version restrictions xD.

After some testing, I came to the below two potential solutions:

1. Remove the version restriction in the already meet dependency

```ruby
# snipped .gemspec
s.add_dependency 'addressable'
s.add_dependency 'opt_parse_validator', '~> 0.0.13.5'

# snipped script file
require 'addressable'
require 'opt_parse_validator'
```

2. Remove the already meet dependency all along

```ruby
# snipped .gemspec
s.add_dependency 'opt_parse_validator', '~> 0.0.13.5'

# snipped script file
require 'opt_parse_validator'
```

Currently I would go with 1, as if one day the addressable gem is removed from opt_parse_validator, then using 2 would break everything.

Thoughts ?

**Comment by Drenmi** [comment]
This isn't really related to RuboCop, but I'll try to answer as best I can anyway. 🙂 

In both cases, you're leaving yourself out. Option 2 has some clear issues:

- Dropping `opt_parse_validator` will break the gem.
- If `opt_parse_validator` drops `addressable`, it will break the gem.

However, option 1 isn't without issues:

- If `opt_parse_validator` change to a breaking version of addressable, it might break the gem.

The third option would be to loosen the restriction on `addressable` just a little bit. I wouldn't recommend leaving it out, because obscuring what the dependencies are has the biggest drawbacks. 🙂 

Hope this helps.

**Comment by erwanlr** [comment]
Thanks you!!

Loosen the restriction a bit like you suggested makes sense to be able to check which version was "safe" in case of broken changes :)

```ruby
# snipped .gemspec
s.add_dependency 'addressable', '~> 2.4'
s.add_dependency 'opt_parse_validator', '~> 0.0.13.5'

# snipped script file
require 'addressable'
require 'opt_parse_validator'
```
