### ISSUE TITLE
Option to check Local git changed files only?

### ISSUE THREAD

**Issue by gamesover** [bbatsov/rubocop#5477]
For large project, to rubocop all files is quite slow and usually it is done by CI but not locally.
For local purpose, I expect there is an option I can rubocop modified files only. So I can scan all files changed by me but leave the all files rubocop at CI server.

**Comment by koic** [comment]
I think that you can get the expected behavior with the following shell.

```sh
% git diff --name-only | xargs rubocop
```

**Comment by pocke** [comment]
I agree @koic's suggestion. Or you can use `rubocop $(git diff --name-only)`.
RuboCop excepts non-ruby files that are received as command line arguments. So it works well if the diff has non-ruby files (e.g. when README.md is changed).

And I think we should not add an option for the problem to keep RuboCop simple.

**Comment by mikegee** [comment]
Also, check out [Pronto](https://github.com/prontolabs/pronto). It is focused on making PR comments, but I'm pretty sure you can just run it locally against the changes.

**Comment by rrosenblum** [comment]
I think this question has come up before. If I remember correctly, the general consensus was although it might be nice to have, this isn't something we want to maintain in RuboCop itself. If we were to add support for git, we would also have to add support for all other version control systems.

The only change that I recommend adding to @koic's example is filter out deleted files `git diff --name-only --diff-filter=MA`. RuboCop will blow up if you try to pass in a file that does not exist.

Aside from "lint unpushed", I also use a "lint unmerged" to run RuboCop against all files that I have in a branch that have not been merged into master. 

`{ git diff HEAD --name-only --diff-filter=MA & git diff origin/master..HEAD --name-only --diff-filter=MA; } | sort | uniq`

Use `upstream` instead of `origin` to lint files that haven't been merged into an upstream project.
`{ git diff HEAD --name-only --diff-filter=MA & git diff upstream/master..HEAD --name-only --diff-filter=MA; } | sort | uniq`

**Comment by Drenmi** [comment]
Closing as out of scope, with great alternative solutions by @koic 2nd @rrosenblum.

**Comment by pirj** [comment]
For the future researchers (and myself re-researching this for the third time):

1. to avoid inspecting all the files in case of e.g. a PR that only deletes files, append some existing file to the list that RuboCop would ignore:
```
& echo '.rubocop.yml' }
```

3. to avoid inspecting of files that are excluded in the configuration:
```
        --force-exclusion            Force excluding files specified in the
                                     configuration `Exclude` even if they are
                                     explicitly passed as arguments.
```

After minor refactoring (`| sort | uniq` -> `| sort -u`), ..., and example for GitHub actions:
```
- run: { git diff HEAD --name-only --diff-filter=MA & git diff origin/main..HEAD --name-only --diff-filter=MA & echo .rubocop.yml } | sort -u | xargs bundle exec rubocop --
```

This still has a downside for PRs, as it would diff against `origin/main`, which is not always the base branch for the PR. Leaving this for the future improvement.
